#
# Required environment variables in the travis config
#
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REPO: The docker repository on docker hub where images are stored
#

language: cpp

git:
  submodules: false

stages:
  - name: Prepare build environments
  - name: Build Qbs

jobs:
  include:
    - stage: Prepare build environments
      name: Build Debian stretch docker image
      env:
        - QT_VERSION=5.9.7
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BRANCH || true
      script:
        - docker build -f docker/stretch/Dockerfile -t stretch --build-arg QT_VERSION=${QT_VERSION} --cache-from ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BRANCH docker/stretch/
      after_success:
        - docker tag stretch ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BUILD_NUMBER
        - docker tag stretch ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BRANCH
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BUILD_NUMBER
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BRANCH

    - stage: Build Qbs
      name: Build with Qbs on Debian stretch
      services:
        - docker
      env:
        - QT_VERSION=5.9.7
        - DOCKER_RUN="docker run --rm -v $TRAVIS_BUILD_DIR:/project -w /project --env QBS_AUTOTEST_PROFILE=qt ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BUILD_NUMBER"
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-$TRAVIS_BUILD_NUMBER
      script:
        - $DOCKER_RUN qbs build profile:qt
        - $DOCKER_RUN qbs build -p "autotest-runner" profile:qt

    - stage: Build Qbs
      name: Build with qmake/make on Debian stretch
      services:
        - docker
      env:
        - DOCKER_RUN="docker run --rm -v $TRAVIS_BUILD_DIR:/project -w /project --env QBS_AUTOTEST_PROFILE=qt ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-$TRAVIS_BUILD_NUMBER"
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-$TRAVIS_BUILD_NUMBER
      script:
        - $DOCKER_RUN /usr/local/Qt/5.9.7/gcc_64/bin/qmake -r qbs.pro
        - $DOCKER_RUN make -j $(nproc)
