#
# Required environment variables in the travis config
#
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REPO: The docker repository on docker hub where images are stored
#

language: cpp

git:
  submodules: false

stages:
  - name: Prepare build environments
  - name: Build Qbs

jobs:
  include:
    - stage: Prepare build environments
      name: Build Windows docker image (Qt 5.9.3)
      os: windows
      services:
        - docker
#      before_install:
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#        - docker pull ${DOCKER_USERNAME}/${DOCKER_REPO}:stretch-${QT_VERSION}-$TRAVIS_BRANCH || true
      script:
        - docker build -f docker/windowsservercore/Dockerfile -t stretch --build-arg QT_VERSION=${QT_VERSION} --cache-from ${DOCKER_USERNAME}/${DOCKER_REPO}:windowsservercore-${QT_VERSION}-$TRAVIS_BRANCH docker/windowsservercore/
#      after_success:
#        - docker tag windowsservercore ${DOCKER_USERNAME}/${DOCKER_REPO}:windowsservercore-${QT_VERSION}-$TRAVIS_BUILD_NUMBER
#        - docker tag windowsservercore ${DOCKER_USERNAME}/${DOCKER_REPO}:windowsservercore-${QT_VERSION}-$TRAVIS_BRANCH
#        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:windowsservercore-${QT_VERSION}-$TRAVIS_BUILD_NUMBER
#        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:windowsservercore-${QT_VERSION}-$TRAVIS_BRANCH
